# Generated by Django 6.0.1 on 2026-01-23 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequiredDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=100, verbose_name='Nome do Documento')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Obrigatório')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('estimated_wait_time', models.IntegerField(default=30, help_text='Dias estimados')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetido'), ('in_review', 'Em Análise'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='draft', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(verbose_name='Data e Hora')),
                ('location', models.CharField(default='Loja AIMA Lisboa', max_length=100)),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='Senha Digital')),
                ('process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.process')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nacionalidade')),
                ('passport_number', models.CharField(max_length=50, unique=True, verbose_name='Nº Passaporte')),
                ('phone', models.CharField(max_length=20, verbose_name='Telemóvel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('valid', 'Válido'), ('invalid', 'Inválido')], default='pending', max_length=20)),
                ('admin_feedback', models.TextField(blank=True, help_text='Motivo da rejeição se inválido', null=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='website.process')),
                ('required_doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.requireddoc')),
            ],
        ),
        migrations.AddField(
            model_name='requireddoc',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='website.servicetype'),
        ),
    ]
