# Generated by Django 6.0.1 on 2026-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile_address_profile_nif_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetido'), ('review', 'Em Análise'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='draft', max_length=20),
        ),
    ]
