# Generated by Django 6.0.1 on 2026-02-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Passaporte'),
        ),
    ]
