# Generated by Django 6.0.1 on 2026-02-10 11:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_profile_passport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Documento Anexado', 'verbose_name_plural': 'Documentos Anexados'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['-submission_date'], 'verbose_name': 'Processo de Imigração', 'verbose_name_plural': 'Processos de Imigração'},
        ),
        migrations.AlterModelOptions(
            name='requireddoc',
            options={'verbose_name': 'Documento Necessário', 'verbose_name_plural': 'Documentos Necessários'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Tipo de Serviço', 'verbose_name_plural': 'Tipos de Serviço'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Envio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(verbose_name='Data e Hora do Agendamento'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(default='Loja AIMA Lisboa - Campus Justiça', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='process',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.process', verbose_name='Processo Associado'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='admin_feedback',
            field=models.TextField(blank=True, help_text='Preencher apenas se rejeitar o documento.', null=True, verbose_name='Motivo da Rejeição'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', verbose_name='Ficheiro'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='required_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.requireddoc', verbose_name='Requisito'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente de Validação'), ('valid', 'Válido / Aceite'), ('invalid', 'Inválido / Rejeitado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='process',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.servicetype', verbose_name='Tipo de Visto'),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho (Em Preenchimento)'), ('submitted', 'Submetido (Aguardar Análise)'), ('review', 'Em Análise Técnica'), ('approved', 'Aprovado (Pronto p/ Agendar)'), ('rejected', 'Rejeitado / Devolvido')], default='draft', max_length=20, verbose_name='Estado Atual'),
        ),
        migrations.AlterField(
            model_name='process',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='process',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Morada Completa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nif',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport',
            field=models.CharField(default='00000', max_length=20, verbose_name='Número de Passaporte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requireddoc',
            name='is_mandatory',
            field=models.BooleanField(default=True, verbose_name='É Obrigatório?'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(verbose_name='Descrição do Requisito'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='estimated_wait_time',
            field=models.IntegerField(default=30, verbose_name='Tempo Estimado (Dias)'),
        ),
    ]
