# Generated by Django 6.0.1 on 2026-03-06 09:48

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_appointment_options_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', validators=[website.models.validate_file_extension_and_size], verbose_name='Ficheiro'),
        ),
    ]
